# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sana < Formula
  desc "A simple terminal-based expense tracker built with Go"
  homepage "https://github.com/kyawphyothu/sana"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyawphyothu/sana/releases/download/v0.1.4/sana_Darwin_x86_64.tar.gz"
      sha256 "67cf02de5809fa2e1c24bb06854582867a49df9759bd35848437882fd86881f6"

      def install
        bin.install "sana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyawphyothu/sana/releases/download/v0.1.4/sana_Darwin_arm64.tar.gz"
      sha256 "00879c9d1313431ddc0b1434cd08b000d73dc4a92e77b37fd15c3b4d1fa3db98"

      def install
        bin.install "sana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyawphyothu/sana/releases/download/v0.1.4/sana_Linux_x86_64.tar.gz"
      sha256 "77805280b1df80db3ffa1cb6be16cd50485703fa0a312eb4f76d1885e0f036d0"
      def install
        bin.install "sana"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyawphyothu/sana/releases/download/v0.1.4/sana_Linux_arm64.tar.gz"
      sha256 "b703f1b274c88e470086f8b8f6506cedfd779020460961556f86a6279813f441"
      def install
        bin.install "sana"
      end
    end
  end
end
