# This file was generated by GoReleaser. DO NOT EDIT.
cask "sana" do
  name "sana"
  desc "A simple terminal-based expense tracker built with Go"
  homepage "https://github.com/kyawphyothu/sana"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sana"

  on_macos do
    on_intel do
      url "https://github.com/kyawphyothu/sana/releases/download/v#{version}/sana_Darwin_x86_64.tar.gz",
        verified: "github.com/kyawphyothu/sana"
      sha256 "e04d5bf30d75389b5ae480ef8f5e9a3e7ac4e63878a92b6191de6b58301aace0"
    end
    on_arm do
      url "https://github.com/kyawphyothu/sana/releases/download/v#{version}/sana_Darwin_arm64.tar.gz",
        verified: "github.com/kyawphyothu/sana"
      sha256 "00289729943b40404b00145b5c493799fb9ef32847fa4abf3f091ff37cb78663"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kyawphyothu/sana/releases/download/v#{version}/sana_Linux_x86_64.tar.gz",
        verified: "github.com/kyawphyothu/sana"
      sha256 "323927e818ea0b5c1b0c4246cd1f9aefaa595b9091d2ade82283bfce75b55466"
    end
    on_arm do
      url "https://github.com/kyawphyothu/sana/releases/download/v#{version}/sana_Linux_arm64.tar.gz",
        verified: "github.com/kyawphyothu/sana"
      sha256 "1731bcb68b80fecfeb5794f1d78e90d75a2a0d5353f687a22a035faa258b3786"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sana"]
    end
  end

  # No zap stanza required
end
